### ISSUE TITLE
Scrape out FFmpeg so we can use a subrepository

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/ElectroMedia-Core#14]

**Comment by etkirsch** [comment]
Can you share that page you gave me a while back? So I can reference it here.

**Comment by NullVoxPopuli** [comment]
https://medium.com/@porteneuve/mastering-git-submodules-34c65e940407

http://blogs.atlassian.com/2013/03/git-submodules-workflows-tips/

**Comment by etkirsch** [comment]
Closed thanks to @NullVoxPopuli
