### ISSUE TITLE
Too few analyzers

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/ElectroMedia-Core#9]
Need more analyzers after 0.2.0.0 release. There should be at least 10.

**Comment by etkirsch** [comment]
@NullVoxPopuli any ideas for these? Like, if you were looking through an audio file, what would you be interested to see?

**Comment by NullVoxPopuli** [comment]
- time signature
 - rhythm (I guess represented as quarter, eighth, twelfth notes, etc)
 - the "hook" (usually this is a handful of notes)
 
Maybe some way to measure energy over time? like.. fast songs can be chill and slow songs can be high energy.. just depends on how the instruments are played

?

**Comment by etkirsch** [comment]
Hook? What do you mean?

**New Analyzers**
* Time signature -> Pattern
* Meter (AKA Rhythm) -> Pattern

Intensity (AKA Energy) already *exists* but is not implemented yet. I don't know of a good equation for that.

**Comment by NullVoxPopuli** [comment]
hook - the short melody thing that pop songs have that makes them catchy.
